language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  postgresql: "9.5"

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

env:
  global:
    - SECRET_KEY=hunter1
    - DATABASE_URL='postgres://postgres@localhost:5432/radioscraper_test'

before_script:
  - createdb -U postgres radioscraper_test
  - python manage.py migrate

script: pytest
